[project]
name = "fias-public-api"
version = "1.0.0"
description = "Python client for FIAS Public API - Russian address database"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [
    {name = "invoxy", email = "quonaro@mail.ru"}
]
keywords = ["fias", "russia", "address", "api", "nalog"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dependencies = [
    "requests>=2.32.5",
]

[project.urls]
Homepage = "https://github.com/invoxy/fias-public-api"
Repository = "https://github.com/invoxy/fias-public-api"
Documentation = "https://github.com/invoxy/fias-public-api#readme"
Issues = "https://github.com/invoxy/fias-public-api/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["fias_public_api"]

[tool.hatch.metadata]
allow-direct-references = true
